<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ET-C02T91MYG8WN.local" ignored="0" name="Login-test-Android" tests="4" failures="1" timestamp="2021-03-22T17:23:23 IST" time="39.371" errors="0">
  <testcase name="successful_login" time="10.267" classname="com.qa.tests.LoginTest"/>
  <testcase name="unsuccessful_login_wrong_password" time="3.329" classname="com.qa.tests.LoginTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.zzz]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.zzz]
at com.qa.tests.LoginTest.unsuccessful_login_wrong_password(LoginTest.java:87)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- unsuccessful_login_wrong_password -->
  <testcase name="unsuccessful_login_wrong_password_username" time="3.715" classname="com.qa.tests.LoginTest"/>
  <testcase name="unsuccessful_login_wrong_username" time="3.705" classname="com.qa.tests.LoginTest"/>
</testsuite> <!-- Login-test-Android -->
